#ifndef EXTTEXTCAT_VERSION_H
#define EXTTEXTCAT_VERSION_H

#define EXTTEXTCAT_VERSION "3.4.0"
#define EXTTEXTCAT_VERSION_MAJOR 3
#define EXTTEXTCAT_VERSION_MINOR 4
#define EXTTEXTCAT_VERSION_MICRO 0

#endif
